### PR TITLE
PT-28 Date range added for table, refactored js code to fit standards 

### PR DESCRIPTION
**Pull request by timle3**
The table is now represented by data from the specified date range. Code has been modularized into specific components on the page as well as refactored to fit js standards.

### CODE REVIEW

**Comment by hli086** [comment]
I think the file names should follow a consistent style, like kebab-case, snake_case, camelCase, or other styles.
Also, I think the name of the line graph component should be changed to PageloadsGraph or something a bit more descriptive.

**Comment by timle3** [comment]
Okay, I went ahead and renamed the components so that it matches snake_case.

**Review by hli086 — APPROVED** [review]
lgtm

**Review by hyunjoon99 — APPROVED** [review]
lgtm

**Pull request merged**
