### PR TITLE
Simplify the website build process for PT-41

### PR DESCRIPTION
**Pull request by michardy**
This PR allows the website to be built with two commands by simplifying the dependency installation process.

If this PR is accepted the new install process would be to run `npm install`

### CODE REVIEW

**Comment by timle3** [comment]
I don't think the public folder is necessary for our project. It's only there when it's first installed as a place holder. I'd recommend taking it out of the pull request.

**Comment by hli086** [comment]
I think Michael meant that adding the public folder would speed up the process of running and testing out new code in the front-end. But if we decided to add the public folder, then I think we can remove it before the project release.

**Comment by michardy** [comment]
`npm start-script run` fails without index.html

**Review by timle3 — APPROVED** [review]
Clarified pull request, looks good!

**Review by timle3 — APPROVED** [review]

**Review by timle3 — APPROVED** [review]

**Review by hli086 — APPROVED** [review]
lgtm

**Pull request merged**
