### PR TITLE
Pt 23

### PR DESCRIPTION
**Pull request by hyunjoon99**

### CODE REVIEW

**Comment by michardy** [comment]
I am realizing this was another case of unclear requirements.  The header is case sensitive and is either `X-Forwarded-For` or ` X-Real-IP`.  


Edit:  This code may work because it is reading internal Flask variables not headers.  I will have to check what it does

**Comment by hyunjoon99** [comment]
Huh maybe I was just doing it wrong but when I tried those options it wouldn't get the IP from the header. It would grab like 'HTTP X HEADER' instead

**Comment by michardy** [comment]
I am going to have to check.  I may be wrong I don't typically use flask

**Review by michardy — APPROVED** [review]
Internal flask magic makes this work

Tested against Nginx

**Review by jmun10 — APPROVED** [review]
lgtm

**Pull request merged**
