### PR TITLE
Counter endpoint that adds db row

### PR DESCRIPTION
**Pull request by hyunjoon99**

### CODE REVIEW

**Comment by michardy** [comment]
I am realizing that PT-6 was not written clearly.  My understanding was that it should be triggered through an HTTP get request not command line invocation.

**Comment by michardy** [comment]
You should move it under ptracker.py and use a non root path (In other words add something to the URL path specified in the decorator).

**Comment by michardy** [comment]
to avoid timezone concerns I might switch `datetime.today()` out for `datetime.utcnow()`

**Comment by jmun10** [comment]
should we worry about timezone concerns? I am assuming most of our testing will be done in the same timezone. Just want to make sure we're on the same page

**Comment by hyunjoon99** [comment]
Ok i can change that anything else?

**Comment by jmun10** [comment]
I'd say change that and the rest should be good for now.

**Review by jmun10 — COMMENTED** [review]
lgtm

**Review by jmun10 — APPROVED** [review]

**Comment by hli086** [comment]
I got an error `(sqlite3.IntegrityError) NOT NULL constraint failed: pageloads.page_name`. I think the request referrer field was missing in the HTTP request. Not sure if I've done this wrong. Everything else seems good to me.

**Comment by jmun10** [comment]
I would say add a default value for page, something like "NOT_DEFINED". then on line 19 do like 
if request.refferer:
    page = request.referrer

**Review by hli086 — APPROVED** [review]
everything looks good to me

**Pull request merged**
