### PR TITLE
PT-24: added filter function and ignore_list.txt

### PR DESCRIPTION
**Pull request by jmun10**
filterDomains() takes in a domain string as a parameter. filterDomains() checks if any lines in 'ignore_list.txt' are present in provided string. If so, function returns None, otherwise function returns unmodified domain input string

### CODE REVIEW

**Comment by jmun10** [comment]
should i make a new folder titled resources or something and place ignore_list.txt into that? not sure how python projects are normally organized but i don't think ignore_list.txt should lie within .py files.

**Comment by hli086** [comment]
Are we going to check if the domain parameter is None or not inside the function or outside the function?

**Comment by hli086** [comment]
The current path for ignore_list.txt in "iphandle.py" seems to be wrong. Should it be "./ignore_list.txt"? Or do you guys want to move the file somewhere else?

**Comment by jmun10** [comment]
@hli086 a bit confused on your first comment. Are there any instances in which the domain parameter provided to filterDomains() will be None?

**Comment by jmun10** [comment]
also I am going to go ahead and create a resources folder if there is no opposition to it. I think it would make project structure cleaner

**Review by michardy — APPROVED** [review]

**Comment by hli086** [comment]
@jmun10 Sorry for the confusion. I meant getDomain() can return None when there's an exception and if that got passed into filterDomains() then it would be an error.

**Review by hli086 — APPROVED** [review]
everything looks good to me

**Pull request merged**
